In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as dates
import scipy.stats as sp
#import statsmodels.api as sm
from pandas.stats.api import ols
from datetime import datetime
from pylab import rcParams
from scipy.signal import argrelextrema
import sys
import platform
import scipy
rcParams['figure.figsize'] = 15, 10
plt.rc('svg', fonttype = 'svgfont')

In [2]:
useTable = "http://water.usgs.gov/watuse/data/2010/USGSCircular1405-tables1-14.xlsx"

In [15]:
useBook = pd.ExcelFile(useTable)

names = list(useBook.sheet_names)
print(names)

[u'1-TO', u'2-TW', u'2b-TW', u'3-TS', u'3b-TS', u'4-TG', u'4b-TG', u'5-PS', u'6-DO', u'7-IT', u'8-LI', u'9-AQ', u'10-IN', u'11-MI', u'12-PT', u'13-PO,PC', u'14-Trends']

In [57]:

totalWithByCat = pd.read_excel(useTable,'2-TW')
SurfaceWith = pd.read_excel(useTable,'3-TS')
GroundWith = pd.read_excel(useTable,'4-TG')
PublicSupply = pd.read_excel(useTable,'5-PS')

In [61]:
totalWithdrawals = pd.read_excel(useTable, '1-TO',skiprows=3)
totalWithdrawals.drop(['Unnamed: 5','Unnamed: 9','Unnamed: 13','Total.1',
                       'Unnamed: 15','Unnamed: 16'],inplace=True,axis=1)
totalWithdrawals
columns=[('Descriptors','State'),('Descriptors','Population (thousands)'),('Groundwater','Fresh'),
         ('Groundwater','Saline'),('Groundwater','Total'),('Surface Water','Fresh'),
         ('Surface Water','Saline'),('Surface Water','Total'),('All','Fresh'),
         ('All','Saline'),('All','Total')]

totalWithdrawals.columns=pd.MultiIndex.from_tuples(columns)
totalWithdrawals.drop([0],inplace=True,axis=0)

In [83]:
totalWithdrawals['stats','GW percent tot'] = pd.to_numeric(totalWithdrawals['Groundwater','Total'])/pd.to_numeric(totalWithdrawals.ix[54,('Groundwater','Total')])*100 
totalWithdrawals['stats','SW percent tot'] = pd.to_numeric(totalWithdrawals['Surface Water','Total'])/pd.to_numeric(totalWithdrawals.ix[54,('Surface Water','Total')])*100
totalWithdrawals['stats','SW percent'] = pd.to_numeric(totalWithdrawals['Surface Water','Total'])/pd.to_numeric(totalWithdrawals['All','Total'])*100
totalWithdrawals['stats','GW percent'] = pd.to_numeric(totalWithdrawals['Groundwater','Total'])/pd.to_numeric(totalWithdrawals['All','Total'])*100

In [84]:
totalWithdrawals['stats','GW fresh percent tot'] = pd.to_numeric(totalWithdrawals['Groundwater','Fresh'])/pd.to_numeric(totalWithdrawals.ix[54,('Groundwater','Fresh')])*100 
totalWithdrawals['stats','SW fresh percent tot'] = pd.to_numeric(totalWithdrawals['Surface Water','Fresh'])/pd.to_numeric(totalWithdrawals.ix[54,('Surface Water','Fresh')])*100
totalWithdrawals['stats','SW fresh percent'] = pd.to_numeric(totalWithdrawals['Surface Water','Fresh'])/pd.to_numeric(totalWithdrawals['All','Fresh'])*100
totalWithdrawals['stats','GW fresh percent'] = pd.to_numeric(totalWithdrawals['Groundwater','Fresh'])/pd.to_numeric(totalWithdrawals['All','Fresh'])*100

In [87]:
totalWithdrawalsWest = totalWithdrawals[totalWithdrawals['Descriptors','State'].isin(('California','Nevada','Arizona',
                                                                                    'Utah','Oregon','Washington',
                                                                                    'Colorado','New Mexico','Oklahoma',
                                                                                     'Nebraska','Kansas','Texas'))]

In [95]:
totalWithdrawalsWest.ix[:,('stats','GW percent tot')] = totalWithdrawalsWest['Groundwater','Total']/totalWithdrawalsWest['Groundwater','Total'].sum()

c:\winpython-64bit-2.7.10.3\python-2.7.10.amd64\lib\site-packages\pandas\core\indexing.py:476: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [96]:
totalWithdrawalsWest

   Descriptors                        Groundwater               Surface Water  \
         State Population (thousands)       Fresh Saline  Total         Fresh
3      Arizona                   6390        2550      0   2550          3540
5   California                  37300       12300    369  12700         18800
6     Colorado                   5030        1540   19.4   1560          9440
17      Kansas                   2850        3200      0   3200           800
28    Nebraska                   1830        4710   0.13   4710          3320
29      Nevada                   2700        1190   11.9   1200          1420
32  New Mexico                   2060        1570      0   1570          1590
37    Oklahoma                   3750         635   1400   2030          1140
38      Oregon                   3830        2130      0   2130          4600
44       Texas                  25100        6830    884   7710         15800
45        Utah                   2760        1030   92.6   1120          3110
48  Washington                   6720        1600      0   1600          3320

                    All                    stats                            \
   Saline  Total  Fresh Saline  Total GW percent SW percent GW percent tot
3       0   3540   6090      0   6090  41.871921  58.128079      0.0605989
5    6490  25300  31100   6860  38000  33.421053  66.578947       0.301806
6       0   9440  11000   19.4  11000  14.181818  85.818182      0.0370722
17      0    800   4000      0   4000  80.000000  20.000000      0.0760456
28      0   3320   8040   0.13   8040  58.582090  41.293532        0.11193
29      0   1420   2610   11.9   2620  45.801527  54.198473      0.0285171
32      0   1590   3160      0   3160  49.683544  50.316456      0.0373099
37      0   1140   1770   1400   3170  64.037855  35.962145      0.0482414
38      0   4600   6730      0   6730  31.649331  68.350669      0.0506179
44   1280  17100  22600   2160  24800  31.088710  68.951613       0.183222
45    238   3340   4130    331   4460  25.112108  74.887892       0.026616
48   33.1   3350   4920   33.1   4960  32.258065  67.540323      0.0380228

                                                                              \
   SW percent tot GW fresh percent tot SW fresh percent tot SW fresh percent
3        1.287273             3.355263             1.539130        58.128079
5        9.200000            16.184211             8.173913        60.450161
6        3.432727             2.026316             4.104348        85.818182
17       0.290909             4.210526             0.347826        20.000000
28       1.207273             6.197368             1.443478        41.293532
29       0.516364             1.565789             0.617391        54.406130
32       0.578182             2.065789             0.691304        50.316456
37       0.414545             0.835526             0.495652        64.406780
38       1.672727             2.802632             2.000000        68.350669
44       6.218182             8.986842             6.869565        69.911504
45       1.214545             1.355263             1.352174        75.302663
48       1.218182             2.105263             1.443478        67.479675


   GW fresh percent
3         41.871921
5         39.549839
6         14.000000
17        80.000000
28        58.582090
29        45.593870
32        49.683544
37        35.875706
38        31.649331
44        30.221239
45        24.939467
48        32.520325